#Task 1: PDF Loading

In [ ]:
document_text = """
Leave Policy

Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.

Work From Home Policy

Employees may work from home twice per week.
Manager approval is required for additional remote work.

Travel Policy

Travel expenses are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.

Medical Insurance Policy

All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.
"""

In [ ]:
!pip install pypdf

Collecting pypdf
  Downloading pypdf-6.13.2-py3-none-any.whl.metadata (7.2 kB)
Downloading pypdf-6.13.2-py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 6.7 MB/s eta 0:00:00
Installing collected packages: pypdf
Successfully installed pypdf-6.13.2

In [ ]:
!pip install reportlab

Collecting reportlab
  Downloading reportlab-4.5.1-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.7)
Downloading reportlab-4.5.1-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 25.5 MB/s eta 0:00:00
Installing collected packages: reportlab
Successfully installed reportlab-4.5.1

In [ ]:
!pip install reportlab pypdf

Requirement already satisfied: reportlab in /usr/local/lib/python3.12/dist-packages (4.5.1)
Requirement already satisfied: pypdf in /usr/local/lib/python3.12/dist-packages (6.13.2)
Requirement already satisfied: pillow>=9.0.0 in /usr/local/lib/python3.12/dist-packages (from reportlab) (11.3.0)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from reportlab) (3.4.7)

In [ ]:
import os

print(os.getcwd())      # Current folder
print(os.listdir())     # Files in folder

/content
['.config', 'sample_data']

In [ ]:
from reportlab.pdfgen import canvas

pdf_file = "/content/employee_policy.pdf"

c = canvas.Canvas(pdf_file)

lines = [
    "Leave Policy",
    "",
    "Employees receive 12 casual leaves annually.",
    "Employees receive 15 sick leaves annually.",
    "Unused casual leaves cannot be carried forward.",
    "",
    "Work From Home Policy",
    "",
    "Employees may work from home twice per week.",
    "Manager approval is required for additional remote work.",
    "",
    "Travel Policy",
    "",
    "Travel expenses are reimbursed within 30 days.",
    "Original receipts must be submitted for reimbursement.",
    "",
    "Medical Insurance Policy",
    "",
    "All employees are covered under company medical insurance.",
    "Dependent coverage is available for spouse and children."
]

y = 800

for line in lines:
    c.drawString(50, y, line)
    y -= 20

c.save()

print("PDF Created Successfully!")

PDF Created Successfully!

In [ ]:
import os

print(os.listdir('/content'))

['.config', 'employee_policy.pdf', 'sample_data']

In [ ]:
from pypdf import PdfReader

reader = PdfReader("/content/employee_policy.pdf")

text = ""

for page in reader.pages:
    extracted = page.extract_text()
    if extracted:
        text += extracted

print("Original Document:\n")
print(text)

print("\nTotal Characters:", len(text))
print("Total Words:", len(text.split()))

Original Document:

Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy
Employees may work from home twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expenses are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Insurance Policy
All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.


Total Characters: 530
Total Words: 76

#Task 2: Fixed Size Chunking

In [ ]:
def fixed_chunking(text, chunk_size):
    chunks = []

    for i in range(0, len(text), chunk_size):
        chunks.append(text[i:i+chunk_size])

    return chunks

In [ ]:
chunks_100 = fixed_chunking(text,100)

for i,chunk in enumerate(chunks_100):
    print(f"\nChunk {i+1}")
    print(chunk)
    print("Length:",len(chunk))

Chunk 1
Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Length: 100

Chunk 2

Unused casual leaves cannot be carried forward.
Work From Home Policy
Employees may work from home
Length: 100

Chunk 3
twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expens
Length: 100

Chunk 4
es are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Ins
Length: 100

Chunk 5
urance Policy
All employees are covered under company medical insurance.
Dependent coverage is avail
Length: 100

Chunk 6
able for spouse and children.

Length: 30

In [ ]:
chunks_200 = fixed_chunking(text,200)

In [ ]:
chunks_300 = fixed_chunking(text,300)

#Task 3: Recursive Chunking

In [ ]:
!pip install -q langchain langchain-community langchain-text-splitters

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 27.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 42.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 554.9/554.9 kB 27.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 5.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.

In [ ]:
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [ ]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size=200,
    chunk_overlap=20
)

chunks = splitter.split_text(text)

for i,chunk in enumerate(chunks):
    print(f"\nChunk {i+1}")
    print(chunk)

Chunk 1
Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy

Chunk 2
Employees may work from home twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expenses are reimbursed within 30 days.

Chunk 3
Original receipts must be submitted for reimbursement.
Medical Insurance Policy
All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.

In [ ]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size=200,
    chunk_overlap=50
)

In [ ]:
splitter = RecursiveCharacterTextSplitter(
    chunk_size=300,
    chunk_overlap=50
)

#Task 4: Sentence-Based Chunking

In [ ]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import sent_tokenize

sentences = sent_tokenize(text)

for i, s in enumerate(sentences, 1):
    print(f"Sentence {i}:")
    print(s)
    print()

Sentence 1:
Leave Policy
Employees receive 12 casual leaves annually.

Sentence 2:
Employees receive 15 sick leaves annually.

Sentence 3:
Unused casual leaves cannot be carried forward.

Sentence 4:
Work From Home Policy
Employees may work from home twice per week.

Sentence 5:
Manager approval is required for additional remote work.

Sentence 6:
Travel Policy
Travel expenses are reimbursed within 30 days.

Sentence 7:
Original receipts must be submitted for reimbursement.

Sentence 8:
Medical Insurance Policy
All employees are covered under company medical insurance.

Sentence 9:
Dependent coverage is available for spouse and children.

#Task 5: Semantic Chunking

In [ ]:
semantic_chunks = {
    "Leave Policy":
    """
    Employees receive 12 casual leaves annually.
    Employees receive 15 sick leaves annually.
    Unused casual leaves cannot be carried forward.
    """,

    "Work From Home Policy":
    """
    Employees may work from home twice per week.
    Manager approval is required for additional remote work.
    """,

    "Travel Policy":
    """
    Travel expenses are reimbursed within 30 days.
    Original receipts must be submitted for reimbursement.
    """,

    "Medical Insurance Policy":
    """
    All employees are covered under company medical insurance.
    Dependent coverage is available for spouse and children.
    """
}

#Task 6: Chunk Comparison Table

In [ ]:
import pandas as pd

comparison = pd.DataFrame({
    "Chunking Method": [
        "Fixed Size",
        "Recursive",
        "Sentence",
        "Semantic"
    ],
    "Context Preservation": [
        "Low",
        "High",
        "High",
        "Very High"
    ],
    "Retrieval Quality": [
        "Low",
        "High",
        "High",
        "Very High"
    ],
    "Implementation Complexity": [
        "Easy",
        "Medium",
        "Easy",
        "High"
    ]
})

comparison

,Chunking Method,Context Preservation,Retrieval Quality,Implementation Complexity
0,Fixed Size,Low,Low,Easy
1,Recursive,High,High,Medium
2,Sentence,High,High,Easy
3,Semantic,Very High,Very High,High

In [ ]:
print(comparison.to_string(index=False))

Chunking Method Context Preservation Retrieval Quality Implementation Complexity
     Fixed Size                  Low               Low                      Easy
      Recursive                 High              High                    Medium
       Sentence                 High              High                      Easy
       Semantic            Very High         Very High                      High

#Task 7: Retrieval Simulation Table

In [ ]:
retrieval_results = pd.DataFrame({
    "Query":[
        "How many casual leaves are provided?",
        "Can employees work from home?",
        "What is the travel reimbursement process?",
        "Who is covered under medical insurance?"
    ],
    "Chunking Method":[
        "Semantic",
        "Semantic",
        "Semantic",
        "Semantic"
    ],
    "Retrieved Chunk":[
        "Employees receive 12 casual leaves annually.",
        "Employees may work from home twice per week.",
        "Travel expenses are reimbursed within 30 days.",
        "All employees are covered under company medical insurance."
    ]
})

retrieval_results

,Query,Chunking Method,Retrieved Chunk
0,How many casual leaves are provided?,Semantic,Employees receive 12 casual leaves annually.
1,Can employees work from home?,Semantic,Employees may work from home twice per week.
2,What is the travel reimbursement process?,Semantic,Travel expenses are reimbursed within 30 days.
3,Who is covered under medical insurance?,Semantic,All employees are covered under company medica...

#Task 8: Recommendation Report Table

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def retrieve(query, chunks):

    vectorizer = TfidfVectorizer()

    vectors = vectorizer.fit_transform(chunks + [query])

    similarity = cosine_similarity(
        vectors[-1],
        vectors[:-1]
    )

    idx = similarity.argmax()

    return chunks[idx]

In [ ]:
recommendations = pd.DataFrame({
    "Assistant Type":[
        "HR Policy Assistant",
        "Legal Document Assistant",
        "Medical Document Assistant",
        "Research Paper Assistant"
    ],
    "Recommended Chunking":[
        "Semantic",
        "Recursive",
        "Semantic",
        "Recursive"
    ],
    "Reason":[
        "Policies are naturally divided into sections",
        "Legal clauses span multiple paragraphs",
        "Medical topics should remain grouped",
        "Research content flows across sections"
    ]
})

recommendations

,Assistant Type,Recommended Chunking,Reason
0,HR Policy Assistant,Semantic,Policies are naturally divided into sections
1,Legal Document Assistant,Recursive,Legal clauses span multiple paragraphs
2,Medical Document Assistant,Semantic,Medical topics should remain grouped
3,Research Paper Assistant,Recursive,Research content flows across sections

#Auto-Generate Final Summary

In [ ]:
print("="*60)
print("FINAL RECOMMENDATION")
print("="*60)

print("""
1. Fixed Size Chunking
   - Easy to implement
   - Poor context preservation

2. Recursive Chunking
   - Better context retention through overlap
   - Suitable for long documents

3. Sentence Chunking
   - Preserves complete thoughts
   - Good for small documents

4. Semantic Chunking
   - Best retrieval quality
   - Groups related information together

Recommended Strategy for Employee Policy Assistant:
Semantic Chunking
""")

============================================================
FINAL RECOMMENDATION
============================================================

1. Fixed Size Chunking
   - Easy to implement
   - Poor context preservation

2. Recursive Chunking
   - Better context retention through overlap
   - Suitable for long documents

3. Sentence Chunking
   - Preserves complete thoughts
   - Good for small documents

4. Semantic Chunking
   - Best retrieval quality
   - Groups related information together

Recommended Strategy for Employee Policy Assistant:
Semantic Chunking

In [ ]:
comparison.to_csv("chunking_comparison.csv", index=False)

In [ ]:
recommendations.to_csv("recommendation_report.csv", index=False)